services:
  - type: web
    name: bakery-project
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt && python bakery_project/manage.py migrate && python bakery_project/manage.py init_menu && python bakery_project/manage.py collectstatic --no-input"
    startCommand: "gunicorn --chdir bakery_project bakery_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: bakery-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: bakery-db
    plan: free
    databaseName: bakery
    user: bakery
